Updating extension to accomodate running headless for tests and addin…
NetLogo/Reflection-Extension pull request #4
Opened 2017-05-15 17:09 UTC by LaCuneta

…g unit tests.

Switched to the extension context for grabbing the reflection info in all primitives so they'll run headless as well as in NetLogo desktop.  Added unit tests for some of the basic use cases for each primitive.

2017-05-18 18:19 UTC, TheBizzle commented on tests.txt
> +  to-report rev [tacos] set tacos (tacos - 1) report reflection:current-procedure end
[Tacos rule](https://www.youtube.com/watch?v=ljrIFqbmKp8&feature=youtu.be&t=3s)

2017-05-18 18:38 UTC, TheBizzle approved these changes
LGTM

2017-05-18 18:39 UTC, mrerrormessage requested changes
Looks good overall. There's a lot of commented-out code that I would like to see removed before merging.

2017-05-22 20:16 UTC, LaCuneta commented
@mrerrormessage Thanks for looking it over, I removed the extra comment lines from the extension code.  Let me know if there is anything else!

2017-06-02 15:26 UTC, merged